---
- name: Create the /opt/devops directory
  hosts: all
  become: yes
  tasks:
    - name: Ensure /opt/devops directory exists
      ansible.builtin.file:
        path: /opt/devops
        state: directory
        mode: '0755'
    
    - name: Create the info.txt file
      ansible.builtin.copy:
        content: "Hello from Ansible!"
        dest: /opt/devops/info.txt
        mode: '0644'
